spring.application.name=my_store_app
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3316/app_store_database_test}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
spring.main.allow-bean-definition-overriding=true
